texts = {
    'FR':{
        'tag':'ÉVALUATION GRATUITE',
        'home_page_title':'Bienvenue !',
        'home_page_msg':'Évaluez votre maturité data en seulement <strong>2 minutes</strong> et découvrez vos prochaines étapes vers la transformation digitale.',
        'home_page_start_btn':'Démarrer l\'évaluation  →',
        'scan_msg':'Scannez-moi',
        'scan_msg_detail':'Continuez sur mobile',
        'title':'Quiz',
        'end_msg': 'Merci ! Le quiz est terminé.',
        'validate_btn':'Suivant',
        'complete_btn':'Terminer',
        'back_btn':'Précédent',
        'restart_btn':'Recommencer',
        'informations_msg':'Vos informations',
        'info_name':'Nom',
        'info_company':'Entreprise',
        'info_email':'Email',
        'contact_checkbox':"J'accepte d'être recontacté",
        'submit_btn':'Envoyer',
        'saved_info_msg':'Merci ! Vos informations ont été enregistrées.',
        'maturity_msg':'Votre niveau de maturité',
        'empty_field_msg':'Merci de remplir les champs obligatoires.',
        'invalid_email_msg':'Email invalide',
        'url_site':'https://kpcgroup.fr/fr_ca/partenaires-technologiques/kpc-canada-votre-partenaire-data-ti-a-montreal/',
        'scan_msg':'Scannez moi',
    },
    'EN':{
        'tag':'FREE EVALUATION',
        'home_page_title':'Welcome !',
        'home_page_msg':'Evaluate your data maturity in just <strong>2 minutes</strong> and discover your next steps in the digital transformation.',
        'home_page_start_btn':'Start Evaluation  →',
        'scan_msg':'Scan Me',
        'scan_msg_detail':'Continue on mobile',
        'title':'Quiz',
        'end_msg': 'Thank you! The quiz is complete.',
        'validate_btn':'Next',
        'complete_btn':'Complete',
        'back_btn':'Back',
        'restart_btn':'Restart',
        'informations_msg':'Your information',
        'info_name':'Name',
        'info_company':'Company',
        'info_email':'Email',
        'contact_checkbox':'I agree to be contacted',
        'submit_btn':'Submit',
        'saved_info_msg':'Thank you! Your information has been saved.',
        'maturity_msg':'Your maturity level',
        'empty_field_msg':'Please fill the required fields.',
        'invalid_email_msg':'Invalid email',
        'url_site':'https://kpcgroup.fr/en/technological-partners/kpc-canada-your-data-it-partner-in-montreal/',
        'scan_msg':'Scan me',
    }
}