[snowflake]
SNOWFLAKE_USERNAME="connexion_guest"
SNOWFLAKE_PASSWORD="change_me"
SNOWFLAKE_ACCOUNT="mlrpkfc-ho25547"
SNOWFLAKE_WAREHOUSE="COMPUTE_WH"
SNOWFLAKE_DATABASE="DTB_2026_CONNEXION"
SNOWFLAKE_SCHEMA="QUIZZ"